### DISCUSSION TITLE
Reference Variables from Theme.yaml inside Theme.yaml

### DISCUSSION THREAD

**Discussion by HitArrowLegend** [wintercms/winter#129] [Ideas]
Hello, 

I think that it would be nice to be able to use already chosen colors in a color_palette tab, somewhere else in that theme.yaml.
XenForo added that for their 2.0. Let's say a theme has a "color_branding" and a "color_palette" tab in which a user can define all his theme colors.
It would be nice to be able to add tab (or two like for XF2.0) in the current colorpicker to be able to use the already referenced variables so that a user can keep consistency on his website (and not have two slightly different greens that were meant to be the same).

This is how XenForo does it, and it's just amazing in my opinion.

https://puu.sh/HCtPs/26c93a5ddf.png
https://puu.sh/HCtPA/f786f066b8.png
https://puu.sh/HCtPH/a904f77790.png

**Comment by LukeTowers** [comment]
Ooooh, I like that!

**Comment by LeMaX10** [comment]
At the moment, this is also possible. Through the theme settings, you can use colorpicker, and output the variables to the css, including the variables of the css itself.

Example:
layout:
```html
<head>
...
<style type="text/css">
    * {
        --primary-color: {{ this.theme.primary_color }};
    }
</style>
...
<link href="{{ 'assets/css/style.css' | theme }}" />
</head>
```

in theme.yaml
```yaml
name: My Theme
# [...]

form:
    fields:
        primary_color:
            label: Primary Color
            comment: The website primary color
            type: colorpicker
            default: #fff
```


in style.css css example:
```css
.myDiv {
   color: var(--primary-color);
}
```
