### DISCUSSION TITLE
Triggering form fields from multiple events

### DISCUSSION THREAD

**Discussion by HitArrowLegend** [wintercms/winter#137] [Ideas]
Hello, 

I think it would be helpful to be able to trigger a form field using multiple events. I'm working on a theme.yaml and it would be very helpful as I could follow the same logic as in the front end.

If A is checked, then B and C would appear. 
If both B and C are checked, then D would appear.

**Comment by HitArrowLegend** [comment]
something like that would be helpful: 

```
                trigger:
                    action: show
                    fields: A, B
                    conditions: checked, unchecked
```
