### DISCUSSION TITLE
Why isn't the relationmanager a field type?

### DISCUSSION THREAD

**Discussion by rubenvanerk** [wintercms/winter#175] [Q&A] [answered]
The relation manager is rendered through a partial, for me this partial is like this 95% of the time:
```
<?= $this->relationRender('relation_name', ['readOnly' => false]) ?>
```
Why isn't there an option to skip the step of creating a partial? Field config could then look something like this:
```
field_name:
            label: Field name
            type: relationmanager
            relationName: relation_name
            readOnly: true
```
The partial being rendered would be like so:
```
<?= $this->relationRender($field->config['relationName'], ['readOnly' => $field->config['readOnly'] ?? false]) ?>
```
I've started to use a general partial that does the same thing, but I was wondering why you would have to create a new partial for every relation manager. Am I missing something?

**Comment by bennothommo** [comment, marked as answer]
It's likely it was never made into a form widget because the Relation widget requires the Relation behavior to be implemented in the controller to work correctly, which in turn requires a relation config to be set up. Probably a few too many steps to make it a true field in that respect.

**Reply by LukeTowers** [reply]
I'm definitely not opposed to having one, probably no need for it to be a full FormWidget since all of the functionality is handled by the RelationController behavior, but we could probably easily enough add a Form Field partial for `relationcontroller` field with the caveat in the docs that you have to take care of the other setup work yourself.

Thanks for the suggestion @rubenvanerk! Feel free to submit a PR implementing the following:

```yaml
field_name_used_as_relation_name_by_default:
    label: Relation
    type: relationcontroller
    relation: real_name_of_relation_if_field_name_isnt_the_real_name
    # support readOnly, disabled, and the form's previewMode in the partial
```
