### DISCUSSION TITLE
dependsOn fields with repeater

### DISCUSSION THREAD

**Discussion by faselunare** [wintercms/winter#188] [Q&A]
Hi, i have 2 models in my plugin
TYPE and POST

Type is simple
- name (a text field)
- type_attributes (a repeater field)

Post has a relation with one Type.

When (in the post form) I select a Type, I would like to see the Type's fields to fill in.
In practice, each post can have variable elements decided by the selected type.

POST FORM
<img width="1045" alt="Schermata 2021-05-25 alle 01 04 13" src="https://user-images.githubusercontent.com/39338657/119416971-21805500-bcf5-11eb-8d39-914174033b4f.png">

TYPE FORM
<img width="1285" alt="Schermata 2021-05-25 alle 01 04 47" src="https://user-images.githubusercontent.com/39338657/119417009-34932500-bcf5-11eb-87cb-d453b2b09bde.png">

TYPES TABLE
<img width="561" alt="Schermata 2021-05-25 alle 01 05 43" src="https://user-images.githubusercontent.com/39338657/119417073-55f41100-bcf5-11eb-9ac6-bb2c6d32eed5.png">

POSTS TABLE
<img width="778" alt="Schermata 2021-05-25 alle 01 06 07" src="https://user-images.githubusercontent.com/39338657/119417110-64dac380-bcf5-11eb-81f6-4ad8609c8f4d.png">

POST FORM
```yaml
        Type:
            label: 'base33.magazine::lang.type'
            nameFrom: name
            # select: type_attributes
            span: full
            required: 1
            type: relation
            tab: TYPE
        Type_attributes:
            label: 'attributes'
            prompt: 'Add new item'
            minItems: '1'
            maxItems: '1'
            style: default
            span: full
            dependsOn: Type
            type: repeater
            tab: TYPE
            form: {  }
```

![Schermata 2021-05-25 alle 01 08 23](https://user-images.githubusercontent.com/39338657/119417259-b5eab780-bcf5-11eb-8f38-14040ff178d1.png)
