### DISCUSSION TITLE
In form calculations

### DISCUSSION THREAD

**Discussion by envas** [wintercms/winter#255] [Q&A] [answered]
I need to perform a calculation in a form. I think I selected the right way - I created field definitions with dependency

```
fields:
   a: ...
   b: ...
   c: ...
   x:
      dependsOn:
            - a
            - b
            - c
```

and the calculation is performed in the model function `filterFields($fields, $context = null)`. Unfortunately, changes on `a` require database access, changes on `b` or `c` do not. To avoid a database roundtrip and improve performace I need to know, which field fired the event or, at least, the old field values. As I discovered, in the `filterFields()` function the model is filled with current form data, not, as I expected, with the original data fetched from the database or nulls in case of creation.

Is there any other way to perform these calculations in standard ways? Or do I have to use JavaScript?

**Comment by LukeTowers** [comment, marked as answer]
You should be able to use getOriginal('attribute_name') to get the original value of the field @envas

**Reply by envas** [reply]
What about the original value, it works fine. However, the calculation in the form does not work for me. The simple calculation for my total price is performed in the `filterFields()` function. The dependency:

```
    total_price:
        label: Total
        dependsOn:
            - quantity
            - unit_price
            - discount
```
works fine, if I modify one of the source fields and move the cursor to the next field. Then everything is recalculated and I can save the form. But if I change for example the unit_price and click directly `Save and Close`, the calculation is executed, I see shortly the updated value in the form total field but in the model remains the old value. The old value remains in the list as well. See the video. What am I doing wrong?

https://user-images.githubusercontent.com/25388570/126855321-90e571a9-ee35-4901-9236-002cbe627298.mp4
