### DISCUSSION TITLE
Dynamic default backend list filter

### DISCUSSION THREAD

**Discussion by envas** [wintercms/winter#356] [Q&A] [answered]
When creating a dynamic list of group filter options, we can use a method name in the modelClass model. But I did not found a way how to set a default filter dynamically.

Example: I have only one status table for all my models

Model Status

```
id    group    code     name
-----------------------------------------
1    QUO     ACT       Quote active
2    QUO     ACC       Quote accepted
3    QUO     DEC       Quote declined 
4    ORD     CRE       Order created
5    ORD     SHP       Order shipped
6    ORD     INV       Order invoiced
``` 

To create a filter group for my quotations I can create a function

``` 
public function getQuoteOptions()
    {
        return Status::where('group','=','QUO')->lists('name', 'id');
    }
```
and reference the function in my config_filter.yaml scope options

```
scopes:
   status:
      label: 'Status'
      conditions: quote_status_id in (:filtered)
      modelClass: Vendor\Plugin\Models\Status
      fromName: name
      options: getQuoteOptions
```

works fine. But now I would like to set the initial filter (filter active when a user opens the list view) for active quotations only. I created a similar method

``` 
public function getQuoteDefaultOptions()
    {
        return Status::where('group','=','QUO')->where('code','=','ACT')->lists('name','id');
    }
```

and I tried to add the reference to the function in my filter definition

```
   default: getQuoteDefaultOptions
```
 and this does not work, it looks like the defaults must be hardcoded. Any idea?
