### DISCUSSION TITLE
Can't get RecordFinder, using useRelation=false, to work properly

### DISCUSSION THREAD

**Discussion by climao** [wintercms/winter#382] [Q&A]
I have Members (hasMany Payments) and Payments (belongsTo Member).

The Member Form uses a partial to render the Payments relation:
```
    ...
    payments:
        label: 'bitstuff.payments::lang.plugin.name'
        type: partial
        path: payment_fields
    ...
```
_payment_fields.htm: 
```
<?= $this->relationRender('payments') ?>
```

The Payment Form uses a RecordFinder to choose which member is making the payment.
Of course, if it is being used from a Member form, the member is already known, so when a Member issues a Payment the payment fields.yaml uses this:
```
...
    member:
        label: 'author.payments::lang.payment_member_label'
        nameFrom: member_number
        descriptionFrom: member_name
        list: $/author/member/models/member/columns.yaml
        span: left
        type: recordfinder
        useRelation: false                           <=== To just use the member's ID
        modelClass: Author\Member\Models\Member      <=== Class of model to use
...     
```     
The problem is that, in the Payment form, the Member does not get initialized properly (i.e. it is **always null**).

<img src="https://user-images.githubusercontent.com/419360/146650944-fa923369-0cda-45ef-9d7f-b322e0667691.png" width="75%" />

I dug a bit and noticed that in Backend\FormWidgets\RecordFinder.php the getLoadValue() function uses:
```
    public function getLoadValue()
    {
        ...
        
            $value = $this->modelClass::where($this->keyFrom, parent::getLoadValue())->first();
        }

        return $value;
    }
```    
which, in my case, is the source of the problem, because $value is always null. 

If I change it to:
```
    ...
    $value = $this->modelClass::where($this->keyFrom, parent::getLoadValue()->{$this->keyFrom})->first(); 
    ...
```
everything works just fine!

Of course, I am assuming there is something wrong with my code...

What am I missing here?
___
This is running in the Winter backend using:
 - Winter CMS build 1.1.7
 - PHP 7.3 
 - MySQL 5.7.
