### DISCUSSION TITLE
How to add the search widget to lists by hand

### DISCUSSION THREAD

**Discussion by pmartinezf** [wintercms/winter#408] [Q&A]
Hello, as it says in the following [link](https://octobercms.com/support/article/ob-20) it is possible to create a list without behaviours, I am trying to add the search widget, but I can not make it work. The idea is to render a list with filters and search inside reportwidget.

**Comment by LukeTowers** [comment]
Do you have a specific question other than "I can not make it work"?

**Reply by pmartinezf** [reply]
Sorry, how can I add a search widget to the list?
```php
$config = $this->makeConfig('$/acme/formist/models/customer/columns.yaml');
$config->model = new \Acme\Formist\Models\Customer;
$customersList = $this->makeWidget('Backend\Widgets\Lists', $config);
```

**Reply by LukeTowers** [reply]
You don't add it to a list directly; you bind them both to the controller and use events to hook them up together. Try looking at the ListController behavior as an example of how to do things that it does: https://github.com/wintercms/winter/blob/develop/modules/backend/behaviors/ListController.php#L201-L273

**Reply by pmartinezf** [reply]
Thank you very much, very kind, your answer has helped me a lot. 
However, in the goup filter types, when it makes the AJAX request to onFilterGetOptions, I get the following error:
![error-filterlist](https://user-images.githubusercontent.com/10201093/150594171-62928b96-5de3-4c0b-98c6-798cc340bfe3.jpg)

In my config_filter.yaml file
```
scopes: 
    month:
        label: "Colegios con datos en los meses"
        type: group
        scope: myScopeHere
        options:
            january: Enero
            february: Febrero
           ...
```
Any suggestions?
