### DISCUSSION TITLE
Support column groupings in DataGrid widget

### DISCUSSION THREAD

**Discussion by Flynsarmy** [wintercms/winter#507] [Ideas]
Large datagrids can look very cluttered and disorganised:
![Screen Shot 2022-03-23 at 6 40 38 pm](https://user-images.githubusercontent.com/334808/159658145-53b9dfbb-d8ca-4fa5-b986-696872db4443.png)

I propose adding a `tab` option for columns which would result in an extra header row and cell borders like so:
![Screen Shot 2022-03-23 at 6 41 59 pm](https://user-images.githubusercontent.com/334808/159658375-160e5483-9b90-4fbc-b10b-5d9b2708cbb2.png)

Example markup:
```yaml
my_field:
    label: Option Matrix
    type: datatable
    searching: true
    columns:
        foo:
            title: Foo
            tab: Options
        bar:
            title: Bar
            tab: Options
        is_disabled:
            title: Disabled
            type: checkbox
            tab: Product
        sku:
            title: SKU
            tab: Product
        images:
            title: Images
            tab: Product
        price:
            title: Price
            tab: Pricing
        cost:
            title: Cost
            tab: Pricing
        is_on_sale:
            title: On Sale
            type: checkbox
            tab: Pricing
        sale_price:
            title: Sale Price or Discount
            tab: Pricing
```

Some thoughts on this proposal:
* `group` would perhaps be a better option name, however that word could potentially be used in the future for collapsing/combining or some other form of grouping of columns. `tab` is consistent with how `FormField` definitions work.
* If one or more columns have a tab and others do not, the extra header row will still appear and the unnamed columns will just be placed into their own blank groups like so (*Disabled* and *Images* columns have no `tab`): 
![Screen Shot 2022-03-23 at 6 50 07 pm](https://user-images.githubusercontent.com/334808/159659941-4ff75166-18f1-4528-85f8-25ab03e9d3e3.png)
* This proposal is backwards compatible, as no existing datatables have columns with a `tab` option, and the extra header row will not appear unless at least one column has a `tab`.

I'm happy to work on this as a PR - just gauging the likelihood of something like this being accepted first.
