### DISCUSSION TITLE
Block access to sensitive field data for unauthorized users

### DISCUSSION THREAD

**Discussion by seanthepottingshed** [wintercms/winter#53] [Q&A] [answered]
- Winter CMS Build: Latest
- PHP Version: 7.2
- Database Engine: mysql
- Plugins Installed: N/A

### Description
Setting a `sensitive` form field to `readOnly` doesn't stop the display of the password when clicking the view button.

### Steps To Reproduce:
And the following to `fields.yaml`:

```yaml
test_api_key:
    label: Test API key
    placeholder: Enter key
    type: sensitive
    readOnly: true
```
