### DISCUSSION TITLE
Dynamically change min/max backend date field (dependsOn)

### DISCUSSION THREAD

**Discussion by ericp-mrel** [wintercms/winter#570] [Q&A]
Hi,

Is it possible to have two date fields e.g. `start date` and `end date` where `end date` is dependent on the start date. So, when a user selects a start date, the end date cannot be earlier than the start date?

I've tried to accomplish this using the `filterFields` method on my model, but I'm assuming the JS widget isn't re-adjusting it's settings as I update the `minDate` config value from the backend code.

Any help is appreciated.

Thanks!

Entry.php:
```php
    /**
     * @param object $fields
     * @param string|null $context
     * @return void
     */
    public function filterFields($fields, $context = null)
    {
        trace_log($fields->entries_end_date);

        if ($fields->entries_start_date->value) {
//            $fields->entries_end_date->minDate = $fields->entries_start_date->value;
            $fields->entries_end_date->config['minDate'] = $fields->entries_start_date->value;

            trace_log($fields->entries_end_date);
        }
    }
```

fields.yaml
```yaml
fields:
    name:
        label: Name
        span: left
        required: 1
        type: text
    entries_section:
        label: Entries
        span: full
        readOnly: 0
        type: section
    entries_start_date:
        label: 'Start Date'
        mode: date
        span: left
        required: 1
        type: datepicker
    entries_end_date:
        label: 'End Date'
        mode: date
        span: auto
        required: 1
        dependsOn:
            - entries_start_date
        minDate: '2022-12-01'
        type: datepicker

```
