### DISCUSSION TITLE
controller instead of model in config_relation

### DISCUSSION THREAD

**Discussion by SledgehammerPL** [wintercms/winter#764] [Q&A] [answered]
Model:
document
id|issuer_id|document_date|document_number

person
id|last_name

and I create two controllers: documents nad people which shows list of documents (with last_name of issuer) and people.

But I want to go further. If I choose person of people's list I will go to field.yaml which shows last_name AND the list of documents issued by this person.

But the list uses model not controller.  

of course because it is set in config_relation.html of people's controller.

```
documents:
  label: Documents
  view:
    list: $/party/structure/models/document/columns.yaml
    toolbarButtons: create
    showSorting: false
    defaultSort:
      column: document_date
      direction: desc
  manage:
    form: $/party/structure/models/document/fields.yaml
```

But I need controller. Because I use ExtendedQuery and ExtendedScope in controller. 
How to use controller instead of model?
