### DISCUSSION TITLE
backend scopes

### DISCUSSION THREAD

**Discussion by SledgehammerPL** [wintercms/winter#781] [Q&A] [answered]
I have model Person. And Controller People which shows all people (it is connected to backend People. Works perfectly

But now I want to have separate list for Two groups (e.g. ladies and Gentleman). A want 2 side-menu buttons: Ladies and Gentleman.

How to do this. 
I was thinking about adding 
```
  public function scopeLadies($query)
    {
    $query->where("sex",'=','F');
  }
  public function scopeGentleman($query)
    {
    $query->where("sex",'=','M');
  }   

```
Then I created new controller Ladies which inherits Person Model, connect this to backend button - and works - shows all people

And then I add `scopes: ladies` in `controllers/ladies/config_list yaml`, but doesn't work....

**Comment by mjauvin** [comment]
Show what you did in `config_list.yaml`

**Comment by SledgehammerPL** [comment]
```
list: $/party/structure/models/person/ladies_columns.yaml
modelClass: Party\Structure\Models\Person
title: Ladies
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'party/structure/people/update/:person_id'
filter: config_filter.yaml
scopes: ladies
```
