### DISCUSSION TITLE
recordfinder searchScope doesn't work

### DISCUSSION THREAD

**Discussion by SledgehammerPL** [wintercms/winter#784] [Q&A] [answered]
why searchScope (with recordfinder) doesn't work? if I put my scopeSth to scope: - it works. But in searchScope: - not at all... 

it doesn't work in winter.test either...

```
fields:
    person:
        label: person
        type: recordfinder
        list:  $/party/structure/models/person/columns.yaml
        useRelation: false
        modelClass: Party\Structure\Models\PersonData
        recordsPerPage: 10
        title: find Record
        keyFrom: person_id
        scope: finderScope
        searchMode: any
        searchScope: getName
        prompt: Click the find button

```

```
 public function scopeFinderScope($query)
    {
    #      $query->where('person_data_last_name','LIKE',"B%");
    }

    public function scopeGetName($query,$type)
    {
      $query->where('person_data_last_name','LIKE',"B%");
    }

```
