### DISCUSSION TITLE
where put extended filter for tab....

### DISCUSSION THREAD

**Discussion by SledgehammerPL** [wintercms/winter#789] [Q&A] [answered]
I want to have a filter in tab - it is quite easy - you have to edit `controllers/XXX/config_relation.yaml` and add `filter:` e.g:

```
organ_members:
  label: Skład
  view:
     list: $/party/structure/models/organmember/columns.yaml
     toolbarButtons: false
     showSearch: true
     scope: allTime
     filter: config_filter2.yaml
  manage:
     list: $/party/structure/models/person/columns.yaml
  pivot:
     form: $/party/structure/models/organmember/fields.yaml

```
and in config_filter2.yaml:
```
scopes:
  organ_member_valid_from:
    type: date
    label: stan na dziś

```

But I want more complex filter. Normally I use
```
 public function listFilterExtendScopes($filter)
    {
      $filter->addScopes([
        'my_advanced_filter' => [
          'label' => 'Stan na dzień',
          'type' => 'date',
          'conditions' => "very complex sql",
          'default' => Carbon::now()
        ]
      ]);
    }
```
But it works in normal columns executed by controller. Not in tabs in form...

So WHERE!? I tried to put it in all related controllers and models. And even formFilterExtendScopes.... Nope. Wrong place:

Undefined array key "my_advanced_filter"
