### DISCUSSION TITLE
hidden sorting doesn't work

### DISCUSSION THREAD

**Discussion by SledgehammerPL** [wintercms/winter#793] [Q&A] [answered]
I'd like to sort list by document_item_id, but I don't want to show this column.

I tried - both results are the same. Not sorted...
```
columns:
    document_item_desc:
        label: opis
        type: text
    document_item_date:
        label: data
        type: date

defaultSort:
    column: document_item_id
    direction: asc

```
```
columns:
    document_item_id:
        invisible: true
    document_item_desc:
        label: opis
        type: text
    document_item_date:
        label: data
        type: date

defaultSort:
    column: document_item_id
    direction: asc

```
