### DISCUSSION TITLE
Datatable field for relation

### DISCUSSION THREAD

**Discussion by WebVPF** [wintercms/winter#829] [Q&A]
Is it possible to use a Datatable field through relations?

I have two models: **Category** and **Item**.

In the category model, I have a relation with Item
plugins\webvpf\plugname\models\Category.php

```php
public $hasMany = [
    'items' => \WebVPF\Plugname\Models\Item::class,
];
```

In field definition I have specified `datatable` field for `items`

plugins\webvpf\plugname\models\category\fields.yaml

```yaml
fields:
    name:
        label: Name category
        type: text

    items:
        type: datatable
        adding: true
        columns:
            id:
                type: string
                title: id
                readOnly: true
            name:
                type: string
                title: Name item
        deleting: false
        # fieldName: null
        keyFrom: id
        recordsPerPage: false
        searching: false
```

The table correctly sees the number of Items, but it does not see the data

![2023-01-30_025859](https://user-images.githubusercontent.com/61043464/215367143-bd8ece52-313c-48d0-aef1-eb2ccf44d946.jpg)

Please tell me how to do it right?
