### DISCUSSION TITLE
Relation form fields

### DISCUSSION THREAD

**Discussion by luciandex** [wintercms/winter#97] [Q&A]
Need some help
I have 3 tables countries and cities and places
Country hasMany cities
City belongsTo  country
Place belongsTo city

Now, I want to make a relation field (backend) that  show City name AND Country name.
I tried concat(name, ' - ', country) but no way for success
I tried some SQL syntax, but failed

My city-country field is:
```yaml
    city:
        span: auto
        select: concat(name, ' - ', country)
        type: relation
        relation: city
```
What supposed to do to properly show city - country?

**Comment by iMateo** [comment]
This question is not related with a core of Winter CMS. You can ask for help in Discord (check readme.md for link)

**Reply by luciandex** [reply]
Mr BennoThommo told me to add the question on Github.
The question is also available at: [https://discord.com/channels/816852513684193281/821159568763125800/834351655457128458](https://discord.com/channels/816852513684193281/821159568763125800/834351655457128458)

**Reply by bennothommo** [reply]
@iMateo it's fine to post questions like this, in case it's something that can be done with a configuration change or some other edit in Winter.

**Comment by rubenvanerk** [comment]
You could do something like this:
```
    city:
        span: auto
        type: relation
        relation: city
        valueFrom: label
```

In your City model add:
```php
public function getLabelAttribute()
{
    return $this->name . ' - ' . $this->country->name;
}
```
