### ISSUE TITLE
Datepicker (datetime) no time at preview mode

### ISSUE THREAD

**Issue by AIC-BV** [wintercms/winter#1065]
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

Like the title suggests, datepicker field with datetime does not show time in preview mode
```
created_at:
        label: Created at
        type: datepicker
        mode: datetime
        format: d/m/Y
        default: now
        span: storm
        cssClass: col-xs-4
```
Ofcourse, the format does not suggest any time.

This format however does, but it shows 00:00 in the date field.
```
created_at:
        label: aic.account::lang.orders.created_at
        type: datepicker
        mode: datetime
        format: d/m/Y H:i
        default: now
        span: storm
        cssClass: col-xs-4
```

### Steps to replicate

See code above

### Workaround

A different field for preview
