### ISSUE TITLE
Multiple default filters interfere with each other

### ISSUE THREAD

**Issue by AIC-BV** [wintercms/winter#1151]
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

When you have multiple defined default filters in `config_filter.yaml` and do the following action:
1. CLEAR the first
2. CLEAR the second
3. Both are CLEARED visually, but in fact, the first has been reset to its default value! It is impossible to clear both filters!
```
approved_status:
        label: Approved status
        type: group
        conditions: approved_status in (:filtered)
        options:
           'x': X
           'y': Y
           'z': Z
        default:
            'x': X

    shipped_status:
        label: Shipped status
        type: group
        conditions: shipped_status in (:filtered)
        options:
            1: Shipped
            0: Not shipped
        default:
            0: Shipped
```

1. ![image](https://github.com/wintercms/winter/assets/89913092/6bbc0ae9-9c33-44eb-b8fb-3a33f017a7a7)
2. ![image](https://github.com/wintercms/winter/assets/89913092/e4c1cb91-e519-49e7-8406-a848dd24d357)
3. ![image](https://github.com/wintercms/winter/assets/89913092/48864646-9ba3-4132-ab3b-ed7db0429308)

### Steps to replicate

See description

**Comment by AIC-BV** [comment]
Also, when you have default filters (doesn't matter wether its single or `multiple),` clear them, and go to the next page, the filters get reapplied and you can never go to the second page

I believe the same happens when you clear and search for something.

**Comment by mjauvin** [comment]
@AIC-BV could you test if this commit has anything to do with this?

https://github.com/wintercms/winter/commit/4847f8bc92b17c689f3ff163f4672ba7155362e4

**Comment by AIC-BV** [comment]
> @AIC-BV could you test if this commit has anything to do with this?
> 
> [4847f8b](https://github.com/wintercms/winter/commit/4847f8bc92b17c689f3ff163f4672ba7155362e4)

I changed my files and ran `php artisan winter:util compile js` but I don't notice any changes. Still not working. Must be broken for years now and an unused functionality 😅

**Comment by bennothommo** [comment]
The problem would be that when a filter is empty, it would instead apply the default value. There's no way for a filter to send a POST value to indicate it is empty and *not* populate the default value.

I had the same issue with an ecommerce site (being able to filter between order status as well as completed or incomplete orders), and I had to change the "completed" filter to a checkbox that, when ticked, only included "completed" orders. You could possibly do the same with your "shipped" filter.

EDIT: These were the scopes I used

```yaml
scopes:
    paid:
        label: Completed orders only
        type: checkbox
        default: 1
        conditions: placed_at IS NOT NULL

    status:
        label: Status
        type: group
        scope: isStatus
        modelClass: \BennoThommo\Snowcart\Models\Status
        options: getList

    placed_at:
        label: Placed at
        type: daterange
        yearRange: 10
        conditions: DATE(placed_at) >= ':afterDate' AND DATE(placed_at) <= ':beforeDate'
```
