### ISSUE TITLE
dependsOn does not work on relation partial if primary field is a dropdown

### ISSUE THREAD

**Issue by goldmont** [wintercms/winter#116]
Hi there,

I have `Farm`, `Order` and `Component` models.
One `Farm` can have many `Components` and many `Orders`; one `Order` can also have `Components`.

I have the following `Order` form:
```yaml
farm:
    label: 'projectx.dashboard::lang.order.form.farm.label'
    placeholder: 'projectx.dashboard::lang.order.form.farm.placeholder'
    required: 1
    showSearch: true
    span: right
    type: dropdown
components:
    context: update
    dependsOn: farm
    deferredBinding: true
    label: 'projectx.dashboard::lang.order.form.components.title'
    type: partial
```

Property `farm` allows to set a `Farm` to which the `Order` belongs to.
Property `components` allows to add a `Component` to an `Order`.

The following `config_relation.yaml`
```yaml
components:
    label: 'projectx.dashboard::lang.order.form.components.entity'
    view:
        list: $/projectx/dashboard/models/componentsorderspivot/columns.yaml
        recordsPerPage: 20
        showCheckboxes: true
        showSearch: true
        toolbarButtons: add|remove
    manage:
        list: $/projectx/dashboard/models/componentsorderspivot/columns.yaml
        recordsPerPage: 20
        scope: byFarm
        showCheckboxes: false
        showSearch: true
    pivot:
        form: $/projectx/dashboard/models/componentsorderspivot/fields.yaml
```

Please, note the `scope: byFarm` property in `manage` section. The scope `byFarm` is implemented correctly like this in `Component` model:
```php
public function scopeByFarm($query, $other)
{
    // $other contains the parent model.
    $query->where('farm_id', $other->farm_id);
}
```

What I want to achieve is to be able to filter the list of `Components` that is shown in the relation popup by the `Farm` ID choosen in the `farm` dropdown without saving and refreshing the page. Currently, I have to select the `farm` I want, then save and refresh the page. It's like, despite the `dependsOn` property, the partial does not refresh automatically sending to the backend the old `Farm` ID instead of the new one selected. `dependsOn` works just fine between two dropdowns but not in this particular case. I think it's a frontend JS issue, not a backend PHP one.

![image](https://user-images.githubusercontent.com/6855692/116011051-3d73d680-a623-11eb-907c-1a5371f00474.png)
