### ISSUE TITLE
Datatable wrong data-field-name if field name with key, and data dont save 

### ISSUE THREAD

**Issue by Trysystems** [wintercms/winter#117]
Datatable widget generates wrong attribute data-field-name. In my case, I extend form with fields with keys (data[1][row], data[2][row]), and widget generates name "Report[data[1][row]]". It's because of logic on 155 string at DataTable.php file.

Temporary fix it with change string to 
`$config->fieldName = $this->getParentForm()->arrayName.'['.implode('][', HtmlHelper::nameToArray($this->fieldName)).']';`

I took logic from FormField class.

**Comment by bennothommo** [comment]
@Trysystems I believe it is set up this way because the data table was originally built for the Builder plugin (I believe?) and that's the format it used. Since it's been like this for years, it may be difficult to make any changes to the naming without breaking implementations of this data type already out there, but we'll look into it further.

**Comment by Trysystems** [comment]
Thank you. This fix shouldn't break anything because "Report[data[1][row]]" wrong structure of field name and it can't work at all, because table.js use this name to create post data, and with wrong name data loses.

**Comment by arvislacis** [comment]
Some backtracking information (may be useful for someone to make PR or test things) - mentioned code part which may contain problem for this issue was introduced in https://github.com/wintercms/winter/commit/970d5622c0deeaeef38c618b42d43b82499fd7f2 as a fix for https://github.com/octobercms/october/issues/4063

**Comment by arvislacis** [comment]
In `fields.yaml`:

```
fields:
    content:
        label: Content
        type: datatable
        columns:
            field1:
                title: Code
            field2:
                title: Title
            field3:
                title: Title
```

![2021-05-03_11-58](https://user-images.githubusercontent.com/626982/116858308-d8157c00-ac06-11eb-8aa3-2f9be290aa6d.png)

^ I made this just for testing purposes and works fine for me. I understand that this is not the format issue author is using but may I ask @Trysystems why you use so specific keys like `data[1][row]` and `data[2][row]` ? Can't you reduce that to similar example I mentioned?

**Comment by Trysystems** [comment]
```
fields:
    content[table]:
        label: Content
        type: datatable
        columns:
            field1:
                title: Code
            field2:
                title: Title
            field3:
                title: Title
```
This will give you data-field-name="Model[content[table]]" attribute now. And js script cant push to server correct data, so you'll receive model[content] empty array.
