### ISSUE TITLE
this.theme.id breaks after adding customization to theme.yaml

### ISSUE THREAD

**Issue by alekseyp** [wintercms/winter#1214]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

When adding fields to theme.yaml , theme.id breaks and returns an integer instead of string (sanitized dirName)

Tested on brand-new setup with demo theme.

```
{{ this.theme.id }}
{{ this.theme.dirName }}
```

```
1
demo
```

### Steps to replicate

- Setup demo theme
- Output `{{ this.theme.id }}` anywhere on the page
- See expected string matching folder name
- Modify theme.yaml adding:
```
form:
    fields:
        site_name:
            label: Site name
            comment: The website name as it should appear on the frontend
            default: My Amazing Site!
```
- refresh the page and see an integer instead of the theme folder name

### Workaround

I've switched to `theme.dirName`, since it's public as well.
