### ISSUE TITLE
Backend anchors have extra styling in firefox

### ISSUE THREAD

**Issue by nmiyazaki-chapleau** [wintercms/winter#1247]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

Firefox adds a blue outline to anchor elements on :focus (which honestly looks horrible) and interferes with the look & feel of WinterCMS.
Some example of problematic places include sections with tabs - on click, which makes the element focused, it add a small blue outline on the left and right side of the element.
Example in the CMS tabs: 
![Image](https://github.com/user-attachments/assets/f7867c77-278a-4003-a85e-df5ac637ef51)
Example in the underlying section:
![Image](https://github.com/user-attachments/assets/8b5db0f8-e2d1-451c-ac44-8fecead46651)

### Steps to replicate

1. Open firefox
2. Go to backend
3. Click on anything that is an anchor

### Workaround

Can be fixed using `a:focus, a:focus-visible { outline: none; }`. However, I do not know if this is intended behavior.

**Comment by damsfx** [comment]
Same for form primary tabs 
![Image](https://github.com/user-attachments/assets/3f5d1e01-e429-4547-9008-eb4dcb45cd3a)

**Comment by LukeTowers** [comment]
So long as the focused element has some form of styling to distinguish it for usability I'd be more than happy to merge any PR suggested. Let me know if you need help submitting one!

**Comment by bennothommo** [comment]
I remember this being added back in the October days. It's horrific. I would very much like a more elegant solution.

**Comment by IsaiahPaget** [comment]
Hey there Luke,

I am a little later than I thought I would be to this. On the same day you reached out to me, I was moved to the second stage of an interview process for a full-time gig, so I had to make sure I studied for that.

This looks like it's something fairly easy to accomplish as a first PR, I loaded up the dev branch and opened the application in Firefox, and lo and behold, it's there. So, from reading the previous comments, it sounds like it's important that the user knows that it's focused, but when using a mouse you get that feedback when the tab is set to active because it comes to the foreground. But there is that scenario when you use the Tab key, and then you can select it that way.

One thing I'd maybe clarify is that: Should the focus ring of all anchor tags be beautified or is it that just the tabs look ugly with the focus ring? As far as I can tell, the real difference between the two browsers is that the focus ring just doesn't show up when you click on the tab in Chrome, but it does when you click on the tab in Firefox.

For reference this is what the focus ring looks like on Chrome

![Image](https://github.com/user-attachments/assets/df251d65-2665-4511-9fbd-5fef6867d1e9)

**Comment by WebVPF** [comment]
@IsaiahPaget @damsfx 
There is such a solution, write the following styles in **Customize back-end**
Backend --> Settings --> Customize back-end --> Styles

```css
.control-tabs.primary-tabs > div > ul.nav-tabs > li a:focus-visible {
    outline: none;
    color: #03a9f4;
}
.master-tabs.control-tabs.fancy-layout > div > div.tabs-container > ul.nav-tabs > li a:focus {
    outline: none;
    color: cyan;
}
.control-tabs> div > ul.nav-tabs > li a:focus > span.title > span,
.control-tabs.primary-tabs > div > ul.nav-tabs > li a:focus > span.title:before,
.control-tabs.primary-tabs > div > ul.nav-tabs > li a:focus > span.title:after {
    border-color: #03a9f4;
}
.control-tabs.primary-tabs > div > ul.nav-tabs > li.active a:focus > span.title span {
    border-top-color: #03a9f4;
}
.fancy-layout *:not(.nested-form) > .form-widget > .layout-row > .control-tabs.primary-tabs > div > ul.nav-tabs > li a:focus {
    color: #2a3e51;
}
```

## Result

![Image](https://github.com/user-attachments/assets/e4500439-9d48-4056-b58c-89d6eee72d6b)

![Image](https://github.com/user-attachments/assets/5f656461-5758-4858-be46-ed14ae1f455d)

## Styles for Dark Backend plugin

```css
body.dark .control-tabs> div > ul.nav-tabs > li a:focus > span.title > span,
body.dark .control-tabs.primary-tabs > div > ul.nav-tabs > li a:focus > span.title:before,
body.dark .control-tabs.primary-tabs > div > ul.nav-tabs > li a:focus > span.title:after {
    border-color: #03a9f4;
}
body.dark .control-tabs.primary-tabs > div > ul.nav-tabs > li.active a:focus > span.title span {
    border-top-color: #03a9f4;
}
body.dark .fancy-layout *:not(.nested-form) > .form-widget > .layout-row > .control-tabs.primary-tabs > div > ul.nav-tabs > li a:focus {
    color: #03A9F4;
}
```
