### ISSUE TITLE
Taglist is saving empty strings

### ISSUE THREAD

**Issue by AIC-BV** [wintercms/winter#1275]
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

![image](https://github.com/user-attachments/assets/08d579f5-e971-485c-98e6-a7bf5a1effd2)
It seems to generate 2 tags instead of one when creating a tag for the first time

When removing all tags, they also save as an empty string
![image](https://github.com/user-attachments/assets/158e1489-f047-49c6-bceb-8f86703a4e92)

When adding tags there is an empty string before the actual first tag
![image](https://github.com/user-attachments/assets/d1fc9d5c-536d-4fb0-a3eb-309fff7b04ac)

### Steps to replicate

```
tags:
    label: Tags
    type: taglist
    customTags: false
    options:
        nieuw: Nieuw
        best: Beste deal
    span: auto
```
