### ISSUE TITLE
Sensitive form widget does not function correctly inside a repeater

### ISSUE THREAD

**Issue by jaxwilko** [wintercms/winter#1321]
### Winter CMS Build

dev-develop

### PHP Version

8.3

### Database engine

MySQL/MariaDB

### Plugins installed

Lots :)

### Issue description

When using `sensitive` in a repeater the value gets replaced by the placeholder on save / on view hidden.

### Steps to replicate

Make a form with the following:
```yaml
fields:
    users:
        type: repeater
        form:
            fields:
                username:
                    label: Username
                    type: text
                    span: auto
                password:
                    label: Password
                    type: sensitive
                    span: auto
```

### Workaround

Use `text` :(
