### ISSUE TITLE
Taglist in relation mode fetches the data twice

### ISSUE THREAD

**Issue by goldmont** [wintercms/winter#1331]
### Winter CMS Build

1.2

### PHP Version

8.2

### Database engine

MySQL/MariaDB

### Issue description

Hi,

I have the following form field:
```yml
assignees:
  label: 'taglist'
  mode: relation
  customTags: false
  nameFrom: id
  options: true
  span: full
  separator: space
  type: taglist
```

I set `options: true` to have the `getAssigneesOptions` method called as the documentation [states](https://wintercms.com/docs/v1.2/docs/backend/forms#tag-list). However, for some reason the taglist control, executes the query by itself and then discards the result in favor of the data returned by the `getAssigneesOptions` method. In fact, I'm forced to set the `nameFrom` property to a valid model attribute in order to make the taglist work.

When setting `options: true`, the taglist control should not execute any query by itself.

### Steps to replicate

1. Create a taglist in relation mode.
2. Set `options: true`
3. Test it.

### Workaround

Set `nameFrom` to a valid model attribute and it works as "expected".
