### ISSUE TITLE
backend datepicker field 'mode date' adds time to the value

### ISSUE THREAD

**Issue by AIC-BV** [wintercms/winter#1358]
### Winter CMS Build

1.2

### PHP Version

8.4

### Database engine

MySQL/MariaDB

### Issue description

I have a datepicker field with mode 'date'.
When saving, I want to do some stuff if the date changed.

The values being logged are
original delivery date: 2025-06-07
new delivery date: 2025-06-07 00:00:00	 

The 'new delivery date' has 00:00:00 after the actual date; meaning the originalIsEquivalent() method keeps returning false because they are not the same. Since I'm using mode 'date' and not 'datetime' I expect the value to be without timestamp.

Right?

### Steps to replicate

I have the following field in my YAML
```yaml
delivery_at:
    context: ['preview', 'update', 'relation']
    tab: Content
    label: Datum
    type: datepicker
    mode: date
    format: d/m/Y
    ignoreTimezone: true
    default: now
    minDate: now
    span: storm
    cssClass: col-xs-4
    trigger:
        action: show
        field: shipping_method
        condition: value[eigen][afhaal]
```
And this code in my Model
```php
public function afterUpdate()
{

    // check if delivery_date has been changed
    if (!$this->originalIsEquivalent('delivery_at')) {
        trace_log('original delivery date: ', $this->getOriginal('delivery_at'));
        trace_log('new delivery date: ', $this->delivery_at);
        trace_log('delivery_at has been changed');
        
        // do something...
    }

}
```

### Workaround

```php
public function afterUpdate()
    {

        // check if delivery_date has been changed
        if (!(
            Carbon::parse($this->getOriginal('delivery_at'))->format('d/m/Y') ===
            Carbon::parse($this->delivery_at)->format('d/m/Y')
        )) {
            trace_log('delivery_at has been changed');

            // do something...

        }

    }
```
☝️ Had to parse because I didn't add `delivery_at` to the $dates array which was the root of the issue
