### ISSUE TITLE
RichEditor form field is not editable if stretch parameter is set

### ISSUE THREAD

**Issue by arvislacis** [wintercms/winter#269]
### Winter CMS Build

dev-develop

### PHP Version

8.0

### Database engine

SQLite

### Issue description

If RichEditor form field has parameter `stretch: 1` set then in simple layout scenario field is not editable in back-end form. With "not editable" I mean the following - field is shown correctly but it's not possible to click with mouse in it and edit it's value.

### Steps to replicate

Example of problematic `fields.yaml`:

```
fields:
    comment:
        label: Comment
        size: giant
        span: full
        required: 1
        stretch: 1
        type: richeditor
```

### Any further details?

Most likely issue arises from `.field-richeditor.stretch .fr-box:not(.fr-fullscreen) .fr-wrapper` selectors `height: auto !important;`.
