### ISSUE TITLE
Form context in controllers in 1.1.4

### ISSUE THREAD

**Issue by YannPl** [wintercms/winter#275]
### Winter CMS Build

1.1.4

### PHP Version

7.4

### Database engine

MySQL/MariaDB

#### In formExtendFields
We are using code like following in our forms:

```
public function formExtendFields($form, $fields){

        dd($form->context); // => displays null

        if ($form->context == 'preview'){
            // do something
        }
        else if ($form->context == 'update'){
            // Do something else
        }
    }
```

It worked properly in version 1.1.3.

#### In fields.yml 
We have fields that depends on the context to display, for example

```
answers:
            label: elipce.backend::lang.surveys.answers
            type: partial
            context: update
            path: field_answers
```
These fields no longer appear in the update form. (neither in any other context)

### Steps to replicate

- Try to log or test the value of $form->context in any `formExtendFields` contoller => value is always null
- Try to make a field display on a specific context like that:
```
answers:
            label: elipce.backend::lang.surveys.answers
            type: partial
            context: update
            path: field_answers
```
=> The field will never be displayed

### Workaround

Downgrade to 1.1.3

### Any further details?

I think there are a global problem with context and our brief tests after upgrade to 1.1.4 only showed 2 use case broken with this bug but it may have broken other things related to contexts
