### ISSUE TITLE
ControllerBehavior Config Maker does not take plugin replacements aliasing into account.

### ISSUE THREAD

**Issue by ericp-mrel** [wintercms/winter#307]
### Winter CMS Build

1.1

### PHP Version

8.0

### Database engine

MySQL/MariaDB

### Issue description

Say you have Acme.Plugin1 and Acme.Plugin2, and Acme.Plugin2 has a controller which implements the RelationController and contains a relation config:

```yaml
# Acme.Plugin2 relation_config.yaml

videos:
  label: Video
  view:
    list: $/acme/plugin1/models/video/relation_columns.yaml
```

And, if the Acme.Plugin1 plugin is forked and changed to Winter.Plugin1 the config lookup for the relation config will still be referencing the old path and will fail to find the file as it does not attempt to alias the config path.

### Steps to replicate

1. Create two plugins `Acme.Plugin1` and `Acme.Plugin2`
2. Create `Video` model in Plugin 1 with a `relation_columns.yaml` file in the model's subfolder (`$/acme/plugin1/models/video/relation_columns.yaml`).
3. Create Dummy controller in Plugin 2 which implements the `RelationController` behavior and create a `relation_config.yaml` file with the following config:

```yaml
videos:
  label: Video
  view:
    list: $/acme/plugin1/models/video/relation_columns.yaml

  [...]
```
