### ISSUE TITLE
Color picker widget don't trigger `dependsOn` event

### ISSUE THREAD

**Issue by damsfx** [wintercms/winter#352]
### Winter CMS Build

dev-develop

### PHP Version

7.4

### Database engine

MySQL/MariaDB

### Issue description

If a backend form field depends on (`dependsOn` attribute) a new color picker widget (winter 1.1.7+); changing color with sliders or by picking an existing on in the palette, it don't fire the refresh event on the linked field.  
Manually editing field value works as expected.

Tested on Windows 10 with
 - Firefox 94.0.2
 - Edge 96.0.1054.29
 - Chrome 96.0.4664.45

### Steps to replicate

In a backend form definition, add the `dependsOn` attribute to a field that point to a color picker field.

```yaml
backdrop_color:
    label: Backdrop color
    span: left
    type: colorpicker
    showAlpha: true
    default: '#C0C0C0CC'
_preview:
    label: Preview
    span: right
    dependsOn:
        - backdrop_color
````
