### ISSUE TITLE
Color picker widget don't allow empty value

### ISSUE THREAD

**Issue by damsfx** [wintercms/winter#353]
### Winter CMS Build

dev-develop

### PHP Version

7.4

### Database engine

MySQL/MariaDB

### Issue description

The new color picker widget (winter 1.1.7+); `allowEmpty` attribute don't work.  
It show the clear button on widget but the button has no action on the field.  
If you manually delete field content (shown a No color placeholder), as soon as the field loses focus the last used color is restored.

Tested on Windows 10 with
 - Firefox 94.0.2
 - Edge 96.0.1054.29
 - Chrome 96.0.4664.45

### Steps to replicate

In a backend form definition, add a `colorpicker` field with `allowEmpty` attribute set to `true`.

```yaml
backdrop_color:
    label: Backdrop color
    span: left
    type: colorpicker
    showAlpha: true
    allowEmpty: true
    default: '#C0C0C0CC'
````
