### ISSUE TITLE
readOnly: true on a type: datepicker is still editable (but grayed out)

### ISSUE THREAD

**Issue by AIC-BV** [wintercms/winter#363]
### Winter CMS Build

1.1

### PHP Version

8.0

### Database engine

MySQL/MariaDB

### Plugins installed

Winter.Sitemap, Winter.Pages, Winter.TinyPNG, Winter.Translate

### Issue description

Models field.yaml
readOnly: true on a type: datepicker is still editable (but grayed out)

```
# ===================================
#  Field Definitions
# ===================================

fields:

    created_at:
        label: aic.account::lang.general.created_at
        type: datepicker
        mode: datetime
        format: d-m-Y
        span: storm
        cssClass: col-xs-6
        readOnly: true
```

### Steps to replicate

Create field with readOnly and type datepicker
