### ISSUE TITLE
dependsOn triggers infinite loop

### ISSUE THREAD

**Issue by Mrkbingham** [wintercms/winter#421]
### Winter CMS Build

1.1

### PHP Version

7.4

### Database engine

MySQL/MariaDB

### Issue description

When a model has two fields that are dependent upon one another, an infinite loop occurs when the dependants are refreshed (line ~189 of winter.form.js: `$('[data-field-name="' + toRefresh.fields[0] + '"]').trigger('change')`

Appears to be related to this update: https://github.com/wintercms/winter/commit/712843d3c231432cefcc3fd5728518e43f73cd33#diff-cf4c08be53eb135693cb4e0424261e5d15c7475d92abc4c87aff32cb81266413

### Steps to replicate

Model setup:
```
alpha_field_one:
    type: switch
    dependsOn:
        - alpha_field_two
alpha_field_two:
    type: switch
    dependsOn:
        - alpha_field_one
```
