### ISSUE TITLE
Improve form repeaters

### ISSUE THREAD

**Issue by jaxwilko** [wintercms/winter#448]
This is a list of notes for things I would like to add, if anybody has any suggestions please add a comment :)

- Add new item under each item (rather than at the bottom and dragging it up)
- Speed up item generation
- Allow items to be dragged between scopes if acceptable
- More span options? (maybe)

**Comment by AIC-BV** [comment]
I noticed that the lazy loading does not work in fields.yaml for a repeater field.
It returns an array but the lazy loading expects a string. Could be an improvement! 😄

EDIT: Hmm forget what I said, its more a bug, it works but in some cases it doesn't. Can't find the reason I'll have to dig deeper.

**Comment by AIC-BV** [comment]
> I noticed that the lazy loading does not work in fields.yaml for a repeater field. It returns an array but the lazy loading expects a string. Could be an improvement! 😄
> 
> EDIT: Hmm forget what I said, its more a bug, it works but in some cases it doesn't. Can't find the reason I'll have to dig deeper.

So I did some deeper digging and found out the following:

Error: `htmlspecialchars(): Argument #1 ($string) must be of type string, array given`
Triggered by: I think it happens when you have a repeater like this in the database.
```
[{
  "name": "My name",
  "remarks": "My remarks",
  "image": "data:image\/jpeg;base64, ...",
  "production": {
      "drawing": "file.pdf",
      "approved_status": 1,
      "remarks": "Ok."
  }
}]
```

I can understand it errors on a base64.
The base64 was only temporary and will be removed and changed to an image path (no worries! 😅)
**But I'm pretty sure it happens on the json object**.

I can read the JSON object like this:
Note that I am using this inside a repeater

```
production[drawing]:
  type: mediafinder

production[approved_status]:
  type: dropdown

production[remarks]:
  type: textarea
```

This is definitely not a required improvement, could work around by splitting the JSON object or not using lazy 😄
Just wanted to let you guys know the issue!

**Comment by AIC-BV** [comment]
Finally found this again! 😌
@jaxwilko I ran into the issue described above again, and it took me a while to figure it out. When I found the solution, I realised I had this problem in the past too...

I am using repeater groups, in which I created a pretty block using a Nestedform because I wanted tabs to make the repeater more compact:
![image](https://user-images.githubusercontent.com/89913092/177555508-6a08bd1b-a437-4ae1-99d2-508e78c49eb7.png)

In fields.yaml
```
blocks:
            tab: aic.blog::lang.form.blocks
            titleFrom: title
            prompt: aic.blog::lang.form.blocks_add
            type: repeater
            cssClass: secondary-tab
            stretch: true
            groups: ~/plugins/aic/extendwinterpages/meta/blocks.yaml
```
In blocks.yaml
```
block_image_with_text:
    name: Image with text
    icon: icon-address-card-o
    fields:
        section:
            label: Image with text
            type: section
        type:
            label: Image
            type: balloon-selector
            default: left
            options:
                left: Left
                right: Right
        data:
            type: nestedform
            usePanelStyles: false
            cssClass: custom-nested-form
            form:
                tabs:
                    icons:
                        Text: icon-keyboard
                        Image: icon-image
                        Link: icon-link
                    fields:
                        title:
                            tab: Text
                            label: Title
                            default: Title
                            type: text
                        text:
                            tab: Text
                            label: Text
                            default: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris nec bibendum nisl. Quisque iaculis feugiat iaculis. Vestibulum lacinia massa vitae nulla blandit, at vestibulum dui malesuada.
                            type: richeditor
                            size: small
...
...
```
This outputs the same type of data as in my post on [24 Feb](https://github.com/wintercms/winter/issues/448#issuecomment-1049725201).
It was giving an error when using lazy for the blocks tab
Error: `htmlspecialchars(): Argument #1 ($string) must be of type string, array given`
The workaround is NOT using lazy for the blocks tab!
