### ISSUE TITLE
Repeater field  - "sortable: false" not working

### ISSUE THREAD

**Issue by ArchimedeSolutions** [wintercms/winter#508]
### Winter CMS Build

1.1

### PHP Version

7.4

### Database engine

MySQL/MariaDB

### Issue description

I would like to be able to block the reordering of the repeater field, despite having set the sortable key to false the items keeps showing the reorder icon and move around if grabbed.
Yaml below:
```
opening_hours:
    commentAbove: 'archisol.mi::lang.restaurants.form.comments.opening_hours'
    context:
        - update
    label: 'archisol.mi::lang.restaurants.form.labels.opening_hours'
    span: left
    type: repeater
    sortable: false
    tab: 'archisol.mi::lang.restaurants.form.tabs.opening_hours'
    form:
        fields:
            day:
                comment: 'archisol.pages::lang.pages.form.links_form.label_comment'
                label: 'archisol.pages::lang.pages.form.links_form.label'
                placeholder: 'archisol.pages::lang.pages.form.links_form.label_placeholder'
                span: full
                type: text
```

### Steps to replicate

Create e repeater field and set `sortable: false`
