### ISSUE TITLE
Repeater titleFrom not working for richeditor

### ISSUE THREAD

**Issue by AIC-BV** [wintercms/winter#679]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Plugins installed

Winter.Sitemap, Winter.Pages, Winter.TinyPNG, Winter.Translate, Winter.Redirects, Aic.Globals, Aic.ExtendWinterPages, Aic.Blog, Aic.Team, Aic.Account, Aic.Contact, Aic.Invoice, Aic.Discount, Aic.Aftersales, Aic.Reviews, Aic.Faq, StudioBosco.BackendNotifications, StudioBosco.BackendComments, ...

### Issue description

Repeater with `titleFrom` attribute does not work with `type:richeditor`. It works with `type:text`. (Did not test other types)
Fine by me, but the it's not mentioned in the [documentation](https://wintercms.com/docs/backend/forms#widget-repeater), which is why it could also be a bug.

Richeditor could be stripped of tags to support this field.
Edit: quick test seems that `textarea` doesn't work either (can be truncated to X characters)

### Steps to replicate

👇 Works with `alt`, does not work with `caption`
```
images:
    tab: Images
    type: repeater
    prompt: Add an image
    style: collapsed
    titleFrom: alt
    form:
        fields:
        image:
            label: Image
            type: mediafinder
            mode: image
            imageWidth: 320
            span: auto
        alt:
            label: Alt attribute
            type: text
            span: auto
        caption:
            label: Figcaption
            type: richeditor
            size: small
  ```

### Workaround

Create an extra field only for the collapsed title, or use another existing field
