### ISSUE TITLE
No longer able to sort relation widget by invisible column

### ISSUE THREAD

**Issue by ericp-mrel** [wintercms/winter#709]
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Plugins installed

Winter.Demo

### Issue description

In October CMS / Winter CMS v1.0 I was able to sort a relation widget by an invisible column as long as I marked all of the other columns as not sortable (`sortable: false`). With Winter CMS v1.1 and v1.2 it seems this doesn't work anymore.

The reason I want to be able to sort by an invisible column is because I've implemented a drag and drop sorting feature for relation widgets to make it easier to sort items for the user. To do this, I utilize a partial column which displays a sort handle icon the user can use to click and drag on and then the actual sort number value was inside an invisible column so the user wouldn't see it and was used so the widget knew what sort order to render everything in.

<img width="1356" alt="Screen Shot 2022-09-22 at 10 32 05 AM" src="https://user-images.githubusercontent.com/63664924/191789722-0daba221-4aca-47e2-b0c9-e5e7904e9beb.png">

![Screen Shot 2022-09-22 at 10 33 39 AM](https://user-images.githubusercontent.com/63664924/191790662-12406108-ec3d-4ea9-bc35-0fcdc4eda238.png)

### Steps to replicate

Test Plugin: [acme.zip](https://github.com/wintercms/winter/files/9627357/acme.zip)

1. Create a new Winter CMS installation
2. Add relation widget to a backend form with no sortable columns except for the invisible `sort_order` column.
3. Create pivot table with sortable column
4. Adjust sort_order column on pivot table and notice the ordering is not affected in the backend form.

Example:
```yaml
# config_relations.yaml

images:
    label: 'Image'
    view:
        showSearch: true
        toolbarButtons: create|add|remove|delete
        form:
            fields:
                name:
                    type: text
                    label: Name
        list:
            columns:
                name:
                    type: text
                    label: Name
                    sortable: false
                'pivot[sort_order]':
                    type: number
                    label: Sort Order
                    invisible: true
                    sortable: true
        defaultSort:
            column: pivot[sort_order]
            direction: asc
    manage:
        showSearch: true
        recordsPerPage: 10
        form:
            fields:
                name:
                    type: text
                    label: Name
        list:
            columns:
                name:
                    type: text
                    label: Name
                    sortable: false
                'pivot[sort_order]':
                    type: number
                    label: Sort Order
                    invisible: true
                    sortable: true
        defaultSort:
            column: created_at
            direction: desc

```

**Comment by ericp-mrel** [comment]
Found a short-term workaround.

It appears I can sort a column which has a type of `partial`.

```yaml
columns:
    [...]
    'pivot[order]':
        label: Sort
        type: partial
        sortable: true
        path: $/acme/test/views/partials/_reorder_handle.php
```

The only thing I don't like about this approach, is it allows the user to adjust the sort direction when the sort direction should only be displayed in ascending order.

![Screen Shot 2022-09-22 at 11 01 25 AM](https://user-images.githubusercontent.com/63664924/191796242-68bcf608-094a-4ef3-829d-37dc3e304ef3.png)
