### ISSUE TITLE
Repeater reorder not working in a repeater with nestedform

### ISSUE THREAD

**Issue by AIC-BV** [wintercms/winter#715]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Plugins installed

Winter.Sitemap, Winter.Pages, Winter.TinyPNG, Winter.Translate, Winter.Redirects, Aic.Globals, Aic.ExtendWinterPages, Aic.Blog, Aic.Team, Aic.Account, Aic.Contact, Aic.Invoice, Aic.Discount, Aic.Aftersales, Aic.Reviews, Aic.Faq, StudioBosco.BackendNotifications, StudioBosco.BackendComments, ...

### Issue description

When reordering repeater items, in a repeater, in a nested form (repeater(groups) > nestedform > repeater > item), items are reordered but saving them does not take any effect.

Below a simplified codeblock 👇 
```
block_gallery:
    name: Gallery
    icon: icon-camera-retro
    fields:
        data:
            type: nestedform
            usePanelStyles: false
            cssClass: custom-nested-form
            form:
                tabs:
                    fields:
                        images:
                            tab: Images
                            type: repeater
                            form:
                                fields:
                                    image:
                                        label: Image
                                        type: mediafinder
                                        mode: image
```
☝️ Note that when reordering the images.image (with the default drag handles on the repeater field), the items are reordered, but saving does not save the new order.

`block_gallery` is located in a repeater with groups
![image](https://user-images.githubusercontent.com/89913092/192534952-25ff92ac-18a9-4905-8f57-a0cae4d1a6b7.png)

Edit:
Reordering the items work fine in StaticPages (using the same yaml code), not in my custom blog plugin

### Steps to replicate

1. Create a plugin using a repeater with groups
2. Link the repeater with groups to the yaml above
3. Try reordering your items in the nestedform repeater
4. Save
5. Refresh (or look at your frontend page)
6. Check and see that your change did not take any effect

### Workaround

I'd love any workaround, if anyone has any suggestions, please let me know!
