### ISSUE TITLE
Trigger events field with ^ parent selector does not work (nestedform)

### ISSUE THREAD

**Issue by AIC-BV** [wintercms/winter#716]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Plugins installed

Winter.Sitemap, Winter.Pages, Winter.TinyPNG, Winter.Translate, Winter.Redirects, Aic.Globals, Aic.ExtendWinterPages, Aic.Blog, Aic.Team, Aic.Account, Aic.Contact, Aic.Invoice, Aic.Discount, Aic.Aftersales, Aic.Reviews, Aic.Faq, StudioBosco.BackendNotifications, StudioBosco.BackendComments, ...

### Issue description

Adding a trigger to your form with the [fields parent selector ](https://wintercms.com/docs/backend/forms#field-trigger-events) does not work

```
block_gallery:
    name: Gallery
    icon: icon-camera-retro
    fields:
        type:
            label: Type
            type: balloon-selector
            default: grid
            options:
                grid: Grid
                slider: Slider
        data:
            type: nestedform
            usePanelStyles: false
            cssClass: custom-nested-form
            form:
                tabs:
                        images:
                            tab: Images
                            type: repeater
                            form:
                                fields:
                                    caption:
                                        label: Caption
                                        type: richeditor
                                        size: small
                                        trigger:
                                            action: hide
                                            field: ^^type
                                            condition: value[grid]
```
No matter how many thingies ^^^ I add, the trigger never happens

### Steps to replicate

1. Create a plugin
2. Use the code above
3. Check the trigger and notice it won't trigger

### Workaround

I added a comment, which is an -ok acceptable- workaround for my case
`commentAbove: Not for type - GRID`

**Comment by LukeTowers** [comment]
@AIC-BV is this still an issue? Did you end up using a workaround?

**Comment by AIC-BV** [comment]
@LukeTowers I still have this issue...
Used the workaround but its not what it is supposed to be
I have it in a new project so it must be there still

fields.yaml
```
# ===================================
#  Field Definitions
# ===================================

tabs:

    icons:
        Blocks: icon-hammer

    fields:

        blocks:
            tab: Blocks
            type: repeater
            groups: ~/plugins/aic/demo/models/issues/blocks.yaml
```

blocks.yaml
```
block_gallery:
    name: Gallery
    icon: icon-camera-retro
    fields:
        type:
            label: Type
            type: balloon-selector
            default: grid
            options:
                grid: Grid
                slider: Slider
        data:
            type: nestedform
            usePanelStyles: false
            cssClass: custom-nested-form
            form:
                tabs:
                        images:
                            tab: Images
                            type: repeater
                            form:
                                fields:
                                    caption:
                                        label: Caption
                                        type: richeditor
                                        size: small
                                        trigger:
                                            action: hide
                                            field: ^^type # No matter the amount of ^, its not triggering
                                            condition: value[grid]
```

**Comment by AIC-BV** [comment]
But it must be very specific to my setup because when I adjust wn-blocks-plugin it is working!
<img width="659" alt="image" src="https://github.com/wintercms/winter/assets/89913092/7975335f-b529-431e-be98-4dc55d343be5">
I guess it does work then

**Comment by AIC-BV** [comment]
I managed to break it here. Test3 (label: Test 2 😅) never gets hidden, no matter the amount of ^. Its hard to say this is my specific case because it works differently in my plugin but it might be the issue I have
<img width="663" alt="image" src="https://github.com/wintercms/winter/assets/89913092/412585d8-4783-49a3-84e7-98c16b85b9b2">

button.block
```
name: winter.blocks::lang.blocks.button.name
description: winter.blocks::lang.blocks.button.description
icon: icon-caret-square-o-right
tags: ["pages"]
fields:
    config:
        type: nestedform
        usePanelStyles: false
        form:
            fields:
                is_delayed:
                    label: Send later
                    comment: Place a tick in this box if you want to send this message at a later time.
                    type: checkbox
                trigger:
                    type: repeater
                    form:
                        fields:
                            test:
                                label: Test
                                span: auto
                                type: text
                                trigger:
                                    action: hide
                                    field: ^is_delayed
                                    condition: checked
                            test2:
                                type: nestedform
                                usePanelStyles: false
                                form:
                                    fields:
                                        test3:
                                            label: Test 2
                                            span: auto
                                            type: text
                                            trigger:
                                                action: hide
                                                field: ^^is_delayed
                                                condition: checked

            tabs:
                icons:
                    winter.blocks::lang.fields.actions: 'icon-arrow-pointer'
                    winter.blocks::lang.tabs.display: 'icon-brush'

                fields:
                    actions:
                        type: repeater
                        tab: winter.blocks::lang.fields.actions
                        prompt: winter.blocks::lang.fields.actions_prompt
                        groups: $/winter/blocks/meta/actions.yaml
                    color:
                        label: winter.blocks::lang.fields.color
                        tab: winter.blocks::lang.tabs.display
                        span: auto
                        type: colorpicker
                    icon:
                        label: winter.blocks::lang.fields.icon
                        tab: winter.blocks::lang.tabs.display
                        span: auto
                        type: iconpicker
==
```
