### ISSUE TITLE
Setting default value in fields.yaml doesn't work

### ISSUE THREAD

**Issue by hirisov** [wintercms/winter#870]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

setting default value for numeric and text fields (maybe others too) in fields.yaml doesn't work.

### Steps to replicate

Add a test field to any model's fields.yaml then open the corresponding form in  the backend

```
        test_field:
            label: 'Test field'
            type: number
            default: 1
```
The field initial (default) value will be empty, instead of 1. Same happens if I try `type: text`.
