### ISSUE TITLE
Some labels are invisible in List Controller due to inline "display: none;" style

### ISSUE THREAD

**Issue by goldmont** [wintercms/winter#88]
Hi there,

after moving to WinterCMS, controllers lists got broken. As you can see from the attached image, the title column content is invisible because an inline "display: none;" style is attached somehow. I didn't managed to solve this issue and I don't understand why this happens only on that column. Hope there's a solution. Thank you for your efforts.

```yaml
columns:
    title:
        label: Title
        type: text
    status:
        label: Completed
        searchable: false
        sortable: true
        type: switch
        width: 10%

```

Result:
![image](https://user-images.githubusercontent.com/6855692/115130317-329bbf00-9fef-11eb-98d0-15d6b4f8a981.png)
