### ISSUE TITLE
Only JSON fields in fields.yaml are being saved

### ISSUE THREAD

**Issue by AIC-BV** [wintercms/winter#883]
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

I have a JSON field in my DB.
It has 2 fields:
- Name
- Code

When Code is not in fields.yaml,
Saving the model will remove the key/value of code instead of keeping it.
![image](https://user-images.githubusercontent.com/89913092/230011421-08a02974-546b-4270-a2d5-50c818b5a17a.png)

### Steps to replicate

My actual case is a repeater with a Nested form
`[{"order":{"name":"Winter","code":"CMS"}}]`

But it also happens without Nested form
`[{"name":"Winter","code":"CMS"}]`

Let's say this is my fields.yaml:
```
tabs:
    fields:
        json:
            tab: JSON
            type: repeater
            titleFrom: item[name]
            form:
                fields:
                    name:
                        label: Name
                    # IF YOU COMMENT THIS, SAVING WILL FORGET THIS KEY/VALUE INSTEAD OF KEEPING IT.
                    code:
                        label: Code
```
If you comment code, and save the model, it will forget about code and only save name. It only saves the fields present in the fields.yaml and forgets about the other fields.
`[{"name":"Winter"}]`

I expected it to only update name in this case and keep code as is.

### Workaround

Create each field of the JSON object in fields.yaml or remove the save button (as long as you don't save it won't forget the fields)

For me however, this isn't really an option. I need certain fields only for technical reasons, and they do not need to be visualized in the backend.
The fields often change and/or new ones are added. I chose for JSON because it would've been more flexible than adding a new field to my entire database (and fields.yaml) everytime.

**Comment by WebVPF** [comment]
NameModel.php

```php
protected $jsonable = [
    'nameJsonField'
];
```

fields.yaml

```yaml
tabs:
    fields:
        nameJsonField:
            tab: JSON
            type: repeater
            titleFrom: item[name]
            form:
                fields:
                    name:
                        label: Name
                    code:
                        label: Code
```

https://wintercms.com/docs/database/model#property-jsonable
